/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import MainPackage.ui.anggota.AnggotaView;
import MainPackage.ui.anggota.repository.AnggotaRepository;
import MainPackage.ui.buku.BukuView;
import MainPackage.ui.buku.repository.BukuRepository;
import MainPackage.ui.kategori.KategoriView;
import MainPackage.ui.kategori.repository.KategoriRepository;
import MainPackage.ui.petugas.PetugasView;
import MainPackage.ui.petugas.repository.PetugasRepository;

/**
 *
 * @author praset
 */
public class MainFormNew extends javax.swing.JFrame {
    
    private KategoriRepository kategoriRepo = new KategoriRepository();
    private BukuRepository bukuRepo = new BukuRepository();
    private AnggotaRepository anggotaRepo = new AnggotaRepository();
    private PetugasRepository petugasRepo = new PetugasRepository();

    private KategoriView kategoriView = new KategoriView(kategoriRepo);
    private BukuView bukuView = new BukuView(bukuRepo);
    private PetugasView petugasView = new PetugasView(petugasRepo);
    private AnggotaView anggotaView = new AnggotaView(anggotaRepo);
    
    /**
     * Creates new form MainFormNew
     */
    public MainFormNew() {
        initComponents();
        addAllPanel();
    }
    
    private void addAllPanel() {
        getContentPane().add(kategoriView);
        getContentPane().add(bukuView);
        getContentPane().add(petugasView);
        getContentPane().add(anggotaView);
        hideAllPanel();
        kategoriView.setVisible(true);
    }
    
    private void hideAllPanel() {
        panelContent.setVisible(false);
        kategoriView.setVisible(false);
        bukuView.setVisible(false);
        petugasView.setVisible(false);
        anggotaView.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuKategori = new javax.swing.JMenuItem();
        menuBuku = new javax.swing.JMenuItem();
        menuRakBuku = new javax.swing.JMenuItem();
        menuPetugas = new javax.swing.JMenuItem();
        menuAnggota = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        getContentPane().add(panelContent, "card2");

        jMenu1.setText("Master");

        menuKategori.setText("Kategori");
        menuKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKategoriActionPerformed(evt);
            }
        });
        jMenu1.add(menuKategori);

        menuBuku.setText("Buku");
        menuBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBukuActionPerformed(evt);
            }
        });
        jMenu1.add(menuBuku);

        menuRakBuku.setText("Rak Buku");
        jMenu1.add(menuRakBuku);

        menuPetugas.setText("Petugas");
        menuPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPetugasActionPerformed(evt);
            }
        });
        jMenu1.add(menuPetugas);

        menuAnggota.setText("Anggota");
        menuAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnggotaActionPerformed(evt);
            }
        });
        jMenu1.add(menuAnggota);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Exit");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKategoriActionPerformed
        hideAllPanel();
        kategoriView.setVisible(true);
    }//GEN-LAST:event_menuKategoriActionPerformed

    private void menuPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPetugasActionPerformed
        hideAllPanel();
        petugasView.setVisible(true);
    }//GEN-LAST:event_menuPetugasActionPerformed

    private void menuAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnggotaActionPerformed
        hideAllPanel();
        anggotaView.setVisible(true);
    }//GEN-LAST:event_menuAnggotaActionPerformed

    private void menuBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBukuActionPerformed
        hideAllPanel();
        bukuView.setVisible(true);
    }//GEN-LAST:event_menuBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFormNew().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAnggota;
    private javax.swing.JMenuItem menuBuku;
    private javax.swing.JMenuItem menuKategori;
    private javax.swing.JMenuItem menuPetugas;
    private javax.swing.JMenuItem menuRakBuku;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
