/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage.ui.laporan_peminjaman;

import MainPackage.Constant;
import MainPackage.Factory.ViewContract;
import MainPackage.ui.anggota.entity.Anggota;
import MainPackage.ui.anggota.repository.AnggotaRepository;
import MainPackage.ui.buku.entity.Buku;
import MainPackage.ui.buku.repository.BukuRepository;
import MainPackage.ui.peminjaman.entity.Peminjaman;
import MainPackage.ui.peminjaman.repository.PeminjamanRepository;
import MainPackage.util.SessionHelper;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author praset
 */
public class LaporanPeminjamanView extends javax.swing.JPanel{
    /**
     * Creates new form PeminjamanViewNew
     * @param repoPeminjaman
     * @param repoBuku
     * @param repoAnggota
     */
    public LaporanPeminjamanView() {
        initComponents();
        loadTable();
    }
    
    private void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama Anggota");
        model.addColumn("Tanggal Peminjaman");
        model.addColumn("Tanggal Kembali");
        model.addColumn("Denda");
        model.addColumn("Judul Buku");
        model.addColumn("Petugas");
        
        try {
            int no = 1;
            String sql = "SELECT" +
            " a.`nama_anggota`," +
            " pj.`tanggal_pinjam`," +
            " pb.`tanggal_pengembalian`," +
            " pb.`denda`," +
            " b.`judul_buku`," +
            " p.`nama_petugas` " +
            "FROM" +
            " peminjaman AS pj," +
            " pengembalian AS pb," +
            " buku AS b," +
            " anggota AS a," +
            " petugas AS p " +
            "WHERE" +
            " pj.`kode_anggota` = a.`kode_anggota`" +
            " AND pj.`kode_buku` = b.`kode_buku`" +
            " AND pj.`id_petugas` = p.`id_petugas`" +
            " AND MONTH(pj.`tanggal_pinjam`) = MONTH(NOW())" +
            " AND YEAR(pj.`tanggal_pinjam`) = YEAR(NOW());";
            java.sql.Connection conn = (Connection) MainPackage.Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)
                });
            }
            tblLaporanPerBulan.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jmcBulan = new com.toedter.calendar.JMonthChooser();
        jycTahun = new com.toedter.calendar.JYearChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporanPerBulan = new javax.swing.JTable();
        btnTampilkan = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setBackground(new java.awt.Color(197, 239, 248));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Laporan Peminjaman Per Bulan");

        jLabel2.setText("Bulan");

        jLabel3.setText("Tahun");

        tblLaporanPerBulan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLaporanPerBulan);

        btnTampilkan.setText("Tampilkan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jmcBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jycTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 178, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jmcBulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jycTahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTampilkan)
                        .addComponent(btnCetak)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        int bulan = jmcBulan.getMonth() + 1;
        int tahun = jycTahun.getYear();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama Anggota");
        model.addColumn("Tanggal Peminjaman");
        model.addColumn("Tanggal Kembali");
        model.addColumn("Denda");
        model.addColumn("Judul Buku");
        model.addColumn("Petugas");
        
        try {
            int no = 1;
            String sql = "SELECT" +
            " a.`nama_anggota`," +
            " pj.`tanggal_pinjam`," +
            " pb.`tanggal_pengembalian`," +
            " pb.`denda`," +
            " b.`judul_buku`," +
            " p.`nama_petugas` " +
            "FROM" +
            " peminjaman AS pj," +
            " pengembalian AS pb," +
            " buku AS b," +
            " anggota AS a," +
            " petugas AS p " +
            "WHERE" +
            " pj.`kode_anggota` = a.`kode_anggota`" +
            " AND pj.`kode_buku` = b.`kode_buku`" +
            " AND pj.`id_petugas` = p.`id_petugas`" +
            " AND MONTH(pj.`tanggal_pinjam`) = '"+bulan+"'" +
            " AND YEAR(pj.`tanggal_pinjam`) = '"+tahun+"';";
            java.sql.Connection conn = (Connection) MainPackage.Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)
                });
            }
            tblLaporanPerBulan.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        int bulan = jmcBulan.getMonth() + 1;
        int tahun = jycTahun.getYear();
        
        try {
            Connection conn = (Connection) MainPackage.Config.configDB();
            JasperDesign jd = JRXmlLoader.load("./src/MainPackage/ui/laporan_peminjaman/laporanPeminjaman.jrxml");
            JRDesignQuery query = new JRDesignQuery();
            String sql = "SELECT" +
            " a.`nama_anggota`," +
            " pj.`tanggal_pinjam`," +
            " pb.`tanggal_pengembalian`," +
            " pb.`denda`," +
            " b.`judul_buku`," +
            " p.`nama_petugas` " +
            "FROM" +
            " peminjaman AS pj," +
            " pengembalian AS pb," +
            " buku AS b," +
            " anggota AS a," +
            " petugas AS p " +
            "WHERE" +
            " pj.`kode_anggota` = a.`kode_anggota`" +
            " AND pj.`kode_buku` = b.`kode_buku`" +
            " AND pj.`id_petugas` = p.`id_petugas`" +
            " AND MONTH(pj.`tanggal_pinjam`) = '"+bulan+"'" +
            " AND YEAR(pj.`tanggal_pinjam`) = '"+tahun+"';";
            query.setText(sql);
            jd.setQuery(query);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException | SQLException ex) {
            Logger.getLogger(LaporanPeminjamanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JMonthChooser jmcBulan;
    private com.toedter.calendar.JYearChooser jycTahun;
    private javax.swing.JTable tblLaporanPerBulan;
    // End of variables declaration//GEN-END:variables

    
}
