/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage.ui.laporan_peminjaman_buku;

import MainPackage.ui.laporan_peminjaman.LaporanPeminjamanView;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author FERDI
 */
public class LaporanPeminjamanBukuView extends javax.swing.JPanel {

    /**
     * Creates new form LaporanPeminjamanBukuView
     */
    public LaporanPeminjamanBukuView() {
        initComponents();
        loadTable();
    }
    
    private void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Judul Buku");
        model.addColumn("Kategori");
        model.addColumn("Penulis");
        model.addColumn("Penerbit");
        model.addColumn("Tahun Terbit");
        model.addColumn("Jumlah Dipinjam");
        
        try {
            int no = 1;
            String sql = "SELECT" +
            " b.`judul_buku`, " +
            " k.`nama_kategori`, " +
            " b.`penulis_buku`, " +
            " b.`penerbit_buku`, " +
            " b.`tahun_penerbit`, " +
            " COUNT(pj.`kode_buku`) AS jml_dipinjam " +
            "FROM " +
            " buku as b, " +
            " kategori as k, " +
            " peminjaman AS pj " +
            "WHERE " +
            " b.`kode_buku` = pj.`kode_buku` AND " +
            " b.`id_kategori` = k.`id_kategori` AND " +
            " MONTH(pj.`tanggal_pinjam`) = MONTH(NOW()) AND" +
            " YEAR(pj.`tanggal_pinjam`) = YEAR(NOW()) " +
            "GROUP BY b.`kode_buku`;";
            java.sql.Connection conn = (Connection) MainPackage.Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)
                });
            }
            tblLaporanBuku.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jmcBulan = new com.toedter.calendar.JMonthChooser();
        jLabel3 = new javax.swing.JLabel();
        jycTahun = new com.toedter.calendar.JYearChooser();
        btnTampilkan = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporanBuku = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Rekap Data Peminjaman Buku");

        jLabel2.setText("Bulan");

        jLabel3.setText("Tahun");

        btnTampilkan.setText("Tampilkan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        tblLaporanBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLaporanBuku);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jmcBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jycTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(btnTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 203, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jmcBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jycTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTampilkan)
                        .addComponent(btnCetak)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        int bulan = jmcBulan.getMonth() + 1;
        int tahun = jycTahun.getYear();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Judul Buku");
        model.addColumn("Kategori");
        model.addColumn("Penulis");
        model.addColumn("Penerbit");
        model.addColumn("Tahun Terbit");
        model.addColumn("Jumlah Dipinjam");
        
        try {
            int no = 1;
            String sql = "SELECT" +
            " b.`judul_buku`, " +
            " k.`nama_kategori`, " +
            " b.`penulis_buku`, " +
            " b.`penerbit_buku`, " +
            " b.`tahun_penerbit`, " +
            " COUNT(pj.`kode_buku`) AS jml_dipinjam " +
            "FROM " +
            " buku as b, " +
            " kategori as k, " +
            " peminjaman AS pj " +
            "WHERE " +
            " b.`kode_buku` = pj.`kode_buku` AND " +
            " b.`id_kategori` = k.`id_kategori` AND " +
            " MONTH(pj.`tanggal_pinjam`) = '"+bulan+"' AND" +
            " YEAR(pj.`tanggal_pinjam`) = '"+tahun+"' " +
            "GROUP BY b.`kode_buku`;";
            java.sql.Connection conn = (Connection) MainPackage.Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)
                });
            }
            tblLaporanBuku.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        int bulan = jmcBulan.getMonth() + 1;
        int tahun = jycTahun.getYear();
        
        try {
            Connection conn = (Connection) MainPackage.Config.configDB();
            JasperDesign jd = JRXmlLoader.load("./src/MainPackage/ui/laporan_peminjaman_buku/laporanPeminjamanBuku.jrxml");
            JRDesignQuery query = new JRDesignQuery();
            String sql = "SELECT" +
            " b.`judul_buku`, " +
            " k.`nama_kategori`, " +
            " b.`penulis_buku`, " +
            " b.`penerbit_buku`, " +
            " b.`tahun_penerbit`, " +
            " COUNT(pj.`kode_buku`) AS jml_dipinjam " +
            "FROM " +
            " buku as b, " +
            " kategori as k, " +
            " peminjaman AS pj " +
            "WHERE " +
            " b.`kode_buku` = pj.`kode_buku` AND " +
            " b.`id_kategori` = k.`id_kategori` AND " +
            " MONTH(pj.`tanggal_pinjam`) = '"+bulan+"' AND" +
            " YEAR(pj.`tanggal_pinjam`) = '"+tahun+"' " +
            "GROUP BY b.`kode_buku`;";
            query.setText(sql);
            jd.setQuery(query);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException | SQLException ex) {
            Logger.getLogger(LaporanPeminjamanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JMonthChooser jmcBulan;
    private com.toedter.calendar.JYearChooser jycTahun;
    private javax.swing.JTable tblLaporanBuku;
    // End of variables declaration//GEN-END:variables
}
